In [3]:
import pandas as pd

In [4]:
train = pd.read_csv('data/train.csv')
train

,id,date,store_nbr,family,sales,onpromotion
0,0,2013-01-01,1,AUTOMOTIVE,0.000,0
1,1,2013-01-01,1,BABY CARE,0.000,0
2,2,2013-01-01,1,BEAUTY,0.000,0
3,3,2013-01-01,1,BEVERAGES,0.000,0
4,4,2013-01-01,1,BOOKS,0.000,0
...,...,...,...,...,...,...
3000883,3000883,2017-08-15,9,POULTRY,438.133,0
3000884,3000884,2017-08-15,9,PREPARED FOODS,154.553,1
3000885,3000885,2017-08-15,9,PRODUCE,2419.729,148
3000886,3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,121.000,8
3000887,3000887,2017-08-15,9,SEAFOOD,16.000,0

In [5]:
stores = pd.read_csv('data/stores.csv')
stores

    store_nbr           city                           state type  cluster
0           1          Quito                       Pichincha    D       13
1           2          Quito                       Pichincha    D       13
2           3          Quito                       Pichincha    D        8
3           4          Quito                       Pichincha    D        9
4           5  Santo Domingo  Santo Domingo de los Tsachilas    D        4
5           6          Quito                       Pichincha    D       13
6           7          Quito                       Pichincha    D        8
7           8          Quito                       Pichincha    D        8
8           9          Quito                       Pichincha    B        6
9          10          Quito                       Pichincha    C       15
10         11        Cayambe                       Pichincha    B        6
11         12      Latacunga                        Cotopaxi    C       15
12         13      Latacunga                        Cotopaxi    C       15
13         14       Riobamba                      Chimborazo    C        7
14         15         Ibarra                        Imbabura    C       15
15         16  Santo Domingo  Santo Domingo de los Tsachilas    C        3
16         17          Quito                       Pichincha    C       12
17         18          Quito                       Pichincha    B       16
18         19       Guaranda                         Bolivar    C       15
19         20          Quito                       Pichincha    B        6
20         21  Santo Domingo  Santo Domingo de los Tsachilas    B        6
21         22           Puyo                         Pastaza    C        7
22         23         Ambato                      Tungurahua    D        9
23         24      Guayaquil                          Guayas    D        1
24         25        Salinas                     Santa Elena    D        1
25         26      Guayaquil                          Guayas    D       10
26         27          Daule                          Guayas    D        1
27         28      Guayaquil                          Guayas    E       10
28         29      Guayaquil                          Guayas    E       10
29         30      Guayaquil                          Guayas    C        3
30         31       Babahoyo                        Los Rios    B       10
31         32      Guayaquil                          Guayas    C        3
32         33        Quevedo                        Los Rios    C        3
33         34      Guayaquil                          Guayas    B        6
34         35         Playas                          Guayas    C        3
35         36       Libertad                          Guayas    E       10
36         37         Cuenca                           Azuay    D        2
37         38           Loja                            Loja    D        4
38         39         Cuenca                           Azuay    B        6
39         40        Machala                          El Oro    C        3
40         41        Machala                          El Oro    D        4
41         42         Cuenca                           Azuay    D        2
42         43     Esmeraldas                      Esmeraldas    E       10
43         44          Quito                       Pichincha    A        5
44         45          Quito                       Pichincha    A       11
45         46          Quito                       Pichincha    A       14
46         47          Quito                       Pichincha    A       14
47         48          Quito                       Pichincha    A       14
48         49          Quito                       Pichincha    A       11
49         50         Ambato                      Tungurahua    A       14
50         51      Guayaquil                          Guayas    A       17
51         52          Manta                          Manabi    A       11
52         53          Manta                          Manabi    D       13
53         54      El Carmen                          Manabi    C        3

In [6]:
train
train = train.drop(['id', 'sales'], axis=1)
train

               date  store_nbr                      family  onpromotion
0        2013-01-01          1                  AUTOMOTIVE            0
1        2013-01-01          1                   BABY CARE            0
2        2013-01-01          1                      BEAUTY            0
3        2013-01-01          1                   BEVERAGES            0
4        2013-01-01          1                       BOOKS            0
...             ...        ...                         ...          ...
3000883  2017-08-15          9                     POULTRY            0
3000884  2017-08-15          9              PREPARED FOODS            1
3000885  2017-08-15          9                     PRODUCE          148
3000886  2017-08-15          9  SCHOOL AND OFFICE SUPPLIES            8
3000887  2017-08-15          9                     SEAFOOD            0

[3000888 rows x 4 columns]

In [7]:
train['family'].unique()

array(['AUTOMOTIVE', 'BABY CARE', 'BEAUTY', 'BEVERAGES', 'BOOKS',
       'BREAD/BAKERY', 'CELEBRATION', 'CLEANING', 'DAIRY', 'DELI', 'EGGS',
       'FROZEN FOODS', 'GROCERY I', 'GROCERY II', 'HARDWARE',
       'HOME AND KITCHEN I', 'HOME AND KITCHEN II', 'HOME APPLIANCES',
       'HOME CARE', 'LADIESWEAR', 'LAWN AND GARDEN', 'LINGERIE',
       'LIQUOR,WINE,BEER', 'MAGAZINES', 'MEATS', 'PERSONAL CARE',
       'PET SUPPLIES', 'PLAYERS AND ELECTRONICS', 'POULTRY',
       'PREPARED FOODS', 'PRODUCE', 'SCHOOL AND OFFICE SUPPLIES',
       'SEAFOOD'], dtype=object)

In [8]:
train['family'] = train['family']
train['family']

0                          AUTOMOTIVE
1                           BABY CARE
2                              BEAUTY
3                           BEVERAGES
4                               BOOKS
                      ...
3000883                       POULTRY
3000884                PREPARED FOODS
3000885                       PRODUCE
3000886    SCHOOL AND OFFICE SUPPLIES
3000887                       SEAFOOD
Name: family, Length: 3000888, dtype: object

pd.get_dummies(pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])pd.get_dummies(])])

In [9]:
train.join(pd.get_dummies(train['family']))

,date,store_nbr,family,onpromotion,AUTOMOTIVE,BABY CARE,BEAUTY,BEVERAGES,BOOKS,BREAD/BAKERY,...,MAGAZINES,MEATS,PERSONAL CARE,PET SUPPLIES,PLAYERS AND ELECTRONICS,POULTRY,PREPARED FOODS,PRODUCE,SCHOOL AND OFFICE SUPPLIES,SEAFOOD
0,2013-01-01,1,AUTOMOTIVE,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2013-01-01,1,BABY CARE,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2013-01-01,1,BEAUTY,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,2013-01-01,1,BEVERAGES,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2013-01-01,1,BOOKS,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3000883,2017-08-15,9,POULTRY,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3000884,2017-08-15,9,PREPARED FOODS,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3000885,2017-08-15,9,PRODUCE,148,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3000886,2017-08-15,9,SCHOOL AND OFFICE SUPPLIES,8,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3000887,2017-08-15,9,SEAFOOD,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [10]:
import torch

class Model(torch.nn.Module):
  def __init__(self):
    self.family = torch.nn.Linear(train['family'])

In [11]:
x = train['date']
x.iloc[2]

'2013-01-01'

In [73]:
import torch
class Dataset(torch.utils.data.Dataset):
  def __init__(self, df):
    self.date = df['date']
    self.store_nb = pd.get_dummies(df['store_nbr'])
    self.family = pd.get_dummies(df['family'])
    self.y = df['sales']
  
  def __len__(self):
    return len(self.date)
  
  def __getitem__(self, idx):
    # date = torch.tensor(self.date.iloc[idx])
    store_nb = torch.from_numpy(self.store_nb.iloc[idx].values).float()
    family = torch.from_numpy(self.family.iloc[idx].values).float()
    return [torch.cat((store_nb, family)), self.y.iloc[idx]]

In [74]:
data = pd.read_csv('./data/train.csv')
dataset = Dataset(data)
dataset.__getitem__(5)[0]

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
from torch import nn

# Starting with a model that ignores the dates
class Model(nn.Module):
  def __init__(self, n):
    super().__init__()
    self.layers = nn.Sequential(
      nn.Linear(n, n),
      nn.ReLU(),
      nn.Linear(n, n),
      nn.ReLU(),
      nn.Linear(n, 1),
      nn.ReLU()
    )
  
  def forward(self, x):
    return self.layers(x)

In [59]:
dataset.__getitem__(0)[0]

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
from torch.utils.data import DataLoader

train = DataLoader(dataset, batch_size=64, shuffle=True)

size = dataset.__getitem__(0)[0].shape[0]
model = Model(size)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
loss_f = nn.MSELoss()

for epoch in range(10):
  running_loss = 0.0
  for i, data in enumerate(train, 0):
    inputs, labels = data
    
    optimizer.zero_grad()
    outputs = model(inputs.float())
    loss = loss_f(outputs, labels.float())
    loss.backward()
    optimizer.step()

    running_loss += loss.item()
    if i % 2000 == 1999:
      print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
      running_loss = 0.0

RuntimeError: "log_softmax_lastdim_kernel_impl" not implemented for 'Long'